# -*- coding: utf-8 -*-
"""01_Time_Converter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HhxgBbj90tgRcsXW7NzvoWal1fxGkV4y
"""

# Function to convert minutes to human readable form

def convert_minutes(total_minutes):
    """
    Converts total minutes (integer) into hours and remaining minutes format.
    Example: 130 becomes "2 hrs 10 minutes"
    """
    if not isinstance(total_minutes, int) or total_minutes < 0:
        return "Invalid input. Please provide a non-negative integer."

    # Integer division for hours
    hours = total_minutes // 60
    # Modulo for remaining minutes
    minutes = total_minutes % 60

    parts = []

    if hours > 0:
        hr_str = "hr" if hours == 1 else "hrs"
        parts.append(f"{hours} {hr_str}")

    # Include minutes if they are non-zero OR if total_minutes was 0
    if minutes > 0 or (hours == 0 and total_minutes == 0):
        min_str = "minute" if minutes == 1 else "minutes"
        parts.append(f"{minutes} {min_str}")

    return " ".join(parts).strip()

# --- Example and Test Cases ---
minutes_list = [130, 110, 60, 59, 1, 0, 1500]

for m in minutes_list:
    print(f"{m} minutes becomes: \"{convert_minutes(m)}\"")