# -*- coding: utf-8 -*-
"""02_Remove_Duplicates.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MTWAgiu9ZT2uy_w3JybgJy2uKwDM8vre
"""

# Function to remove duplicate characters from a string using a loop
def remove_duplicates(input_string):
    """
    Removes duplicate characters from a string using a loop,
    preserving the order of the first occurrence.
    """
    unique_string = ""
    # Use a loop as required by the prompt
    for char in input_string:
        # Check if the character is NOT already in the result string
        if char not in unique_string:
            # If not present, append it
            unique_string += char

    return unique_string

# --- Example and Test Cases ---
test_strings = [
    "programming",
    "aabbccdeeff",
    "K Vignesh",
    "Mississippi"
]

for s in test_strings:
    result = remove_duplicates(s)
    print(f"Original: \"{s}\" -> Unique: \"{result}\"")